# Generated by Django 4.0.6 on 2022-09-13 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_following_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
