# Generated by Django 4.0.6 on 2022-10-01 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_block_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w](?!.*?\\.{2})[\\w.]{1,30}[\\w]$', 'Only letters, numbers, -, ., and _ are allowed.')]),
        ),
    ]
